var data = [
  {
    num: 1,
    name: "강주영",
    id: 2020286001,
    link: "",
    subject: "",
    img: "",
    github: "kangjuyoung98",
  },
  {
    num: 2,
    name: "김다영",
    id: 2018286007,
    link: "https://kim-dayoung.github.io/DIALOGUE-IN-THE-DARK/",
    subject: "어둠속의 대화",
    img: "",
    github: "kim-dayoung",
  },
  {
    num: 3,
    name: "김다인",
    id: 2015286006,
    link: "https://kim-manypeople.github.io/201209_workshop/",
    subject: "아무튼타이포 워크샵데이!",
    img: "",
    github: "kim-manypeople",
  },
  {
    num: 4,
    name: "김동현",
    id: 2020286003,
    link: "https://lemontde.github.io/lemont/",
    subject: "해체주의-김동현 개인전",
    img: "",
    github: "lemontDE",
  },
  {
    num: 5,
    name: "김민정",
    id: 2018286010,
    link: "https://macil7794.github.io/20201216/",
    subject: "바퀴.",
    img: "",
    github: "macil7794",
  },
  {
    num: 6,
    name: "김민지",
    id: 2018286011,
    link: "https://min-jii.github.io/12-15-index/",
    subject: "Dieter Rams “Less, but better”",
    img: "",
    github: "min-jii",
  },
  {
    num: 7,
    name: "김예원",
    id: 2018210118,
    link: "https://ynee.github.io/toalltheboysilovedbefore/",
    subject: "내가 사랑했던 모든 남자들에게",
    img: "",
    github: "ynee",
  },
  {
    num: 8,
    name: "김우용",
    id: 2016286013,
    link: "https://kim-w-yong.github.io/2020test/",
    subject: "DATA ERROR",
    img: "",
    github: "kim-w-yong",
  },
  {
    num: 9,
    name: "김우재",
    id: 2016286014,
    link: "https://hknukwj.github.io/i_love_sandwichh/",
    subject: "샌드위치가 좋아",
    img: "",
    github: "hknuKWJ",
  },
  {
    num: 10,
    name: "김자룡",
    id: 2016286016,
    link: "https://ja-ryong.github.io/wfinal/",
    subject: "사진전-순간",
    img: "",
    github: "ja-ryong",
  },
  {
    num: 11,
    name: "김태훈",
    id: 2016286020,
    link: "",
    subject: "",
    img: "",
    github: "unknown0m0",
  },
  {
    num: 12,
    name: "김혜수",
    id: 2017286011,
    link: "",
    subject: "",
    img: "",
    github: "mozering",
  },
  {
    num: 13,
    name: "백지원",
    id: 2020286009,
    link: "https://jaylinbaek.github.io/kingsman/",
    subject: "Manners Maketh Man 매너가 사람을 만든다",
    img: "",
    github: "JaylinBaek",
  },
  {
    num: 14,
    name: "설예원",
    id: 2018286024,
    link: "https://seol-ye-won.github.io/hill_song/",
    subject: "찬양하세",
    img: "",
    github: "Seol-ye-won",
  },
  {
    num: 15,
    name: "손종인",
    id: 2015286027,
    link: "https://chorokpig.github.io/2020-2-DP-FINAL/",
    subject: "목탁구멍 속의 작은어둠",
    img: "",
    github: "chorokpig",
  },
  {
    num: 16,
    name: "심규민",
    id: 2016286030,
    link: "https://aweek2020.github.io/2020-12-09/",
    subject: "구덩이에서 빠져나는 방법",
    img: "",
    github: "aweek2020",
  },
  {
    num: 17,
    name: "안창현",
    id: 2016286033,
    link: "https://ach0223.github.io/emotion_of_moment/",
    subject: "순간의 감정",
    img: "",
    github: "ach0223",
  },
  {
    num: 18,
    name: "양예지",
    id: 2017286027,
    link: "https://sheep-yg.github.io/1984_final/",
    subject: 1984,
    img: "",
    github: "sheep-yg",
  },
  {
    num: 19,
    name: "오현택",
    id: 2016286036,
    link: "https://earthworm0371.github.io/2020-final/",
    subject: "개성화_홀로 꽃피우기",
    img: "",
    github: "earthworm0371",
  },
  {
    num: 20,
    name: "용의주",
    id: 2013286034,
    link: "https://yongeuijoo.github.io/records_on_venice/",
    subject: "Records on Venice",
    img: "",
    github: "yongeuijoo",
  },
  {
    num: 21,
    name: "이겨례",
    id: 2016286041,
    link: "https://leegyeorye.github.io/20_2-DP2_Final-/",
    subject: "[공백에 관하여.]",
    img: "",
    github: "leegyeorye",
  },
  {
    num: 22,
    name: "이예린",
    id: 2017286036,
    link: "https://mackkam1129.github.io/solor_eclipse/",
    subject: "",
    img: "",
    github: "mackkam25",
  },
  {
    num: 23,
    name: "임민희",
    id: 2017286045,
    link: "https://im-mh.github.io/enjoy-at-home/",
    subject: "PLEASE ENJOY AT HOME",
    img: "",
    github: "im-mh",
  },
  {
    num: 24,
    name: "임세은",
    id: 2018286045,
    link: "",
    subject: "",
    img: "",
    github: "seeun99",
  },
  {
    num: 25,
    name: "임효리",
    id: 2018286047,
    link: "",
    subject: "",
    img: "",
    github: "limhyori",
  },
  {
    num: 26,
    name: "장세리",
    id: 2018286048,
    link: "https://seriij.github.io/1216/",
    subject: "Point of View",
    img: "",
    github: "seriiJ",
  },
  {
    num: 27,
    name: "장진혜",
    id: 2018286050,
    link: "https://jnagjinhye.github.io/dandeli-forgive-poster/",
    subject: 'Dandeli campaign "Forgive',
    img: "",
    github: "jnagjinhye",
  },
  {
    num: 28,
    name: "전혜진",
    id: 2018286051,
    link: "",
    subject: "",
    img: "",
    github: "hyejinjeoneeee",
  },
  {
    num: 29,
    name: "정수진",
    id: 2018286053,
    link: "https://ekfna.github.io/201216_html/",
    subject: "From Earth To Universe",
    img: "",
    github: "ekfna",
  },
  {
    num: 30,
    name: "정의현",
    id: 2018286054,
    link: "https://uihyeon9904.github.io/2020_2_dp11/",
    subject: "흐림 속 진짜 찾기",
    img: "",
    github: "uihyeon9904",
  },
  {
    num: 31,
    name: "최유미",
    id: 2015286054,
    link: "",
    subject: "",
    img: "",
    github: "youandmeworld",
  },
  {
    num: 32,
    name: "한서현",
    id: 2018210181,
    link: "https://working-yy.github.io/DP_final_1216/",
    subject: "DIALOGUE IN THE DARK",
    img: "",
    github: "working-yy",
  },
  {
    num: 33,
    name: "한승규",
    id: 2020286013,
    link: "https://gkstmdrb2008.github.io/12_16/",
    subject: "희미한 것들",
    img: "",
    github: "gkstmdrb2008",
  },
  {
    num: 1,
    name: "고수연",
    id: 2017286001,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 2,
    name: "고승진",
    id: 2015210120,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 3,
    name: "김가람",
    id: 2015286005,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 4,
    name: "김도윤",
    id: 2018286009,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 5,
    name: "김민정",
    id: 2017430004,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 6,
    name: "김소희",
    id: 2017315003,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 7,
    name: "김수홍",
    id: 2016286011,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 8,
    name: "김태유",
    id: 2016286019,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 9,
    name: "문희진",
    id: 2018286017,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 11,
    name: "박희영",
    id: 2017286018,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 12,
    name: "안재균",
    id: 2016286032,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 13,
    name: "여민정",
    id: 2017286028,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 14,
    name: "오혜원",
    id: 2018225024,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 15,
    name: "원혜정",
    id: 2016286038,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 16,
    name: "유지은",
    id: 2018286035,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 17,
    name: "육재경",
    id: 2017286030,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 18,
    name: "이지민",
    id: 2020286011,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 19,
    name: "이진주",
    id: 2018286042,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 20,
    name: "이현중",
    id: 2017286044,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 21,
    name: "임연지",
    id: 2018286046,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 22,
    name: "임영송",
    id: 2017286046,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 23,
    name: "진해인",
    id: 2018286061,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
  {
    num: 24,
    name: "허준",
    id: 2013210114,
    link: "",
    subject: "",
    img: "",
    github: "",
  },
];
